# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\ui_app_sell_abonement.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppSellAbonement(object):
    def setupUi(self, AppSellAbonement):
        AppSellAbonement.setObjectName("AppSellAbonement")
        AppSellAbonement.setWindowModality(QtCore.Qt.ApplicationModal)
        AppSellAbonement.resize(800, 600)
        self.verticalLayoutWidget = QtWidgets.QWidget(AppSellAbonement)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 781, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.table = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.verticalLayout.addWidget(self.table)
        self.gridLayoutWidget = QtWidgets.QWidget(AppSellAbonement)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(150, 10, 521, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.abonementIdSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.abonementIdSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.abonementIdSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.abonementIdSpinBox.setObjectName("abonementIdSpinBox")
        self.gridLayout.addWidget(self.abonementIdSpinBox, 0, 1, 1, 1)
        self.sellButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sellButton.setObjectName("sellButton")
        self.gridLayout.addWidget(self.sellButton, 0, 2, 1, 1)
        self.labelAbonement = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelAbonement.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAbonement.setObjectName("labelAbonement")
        self.gridLayout.addWidget(self.labelAbonement, 0, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.dateEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 1, 1, 1, 1)
        self.oneDayCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.oneDayCheckBox.setObjectName("oneDayCheckBox")
        self.gridLayout.addWidget(self.oneDayCheckBox, 1, 2, 1, 1)
        self.labelDate = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDate.setObjectName("labelDate")
        self.gridLayout.addWidget(self.labelDate, 1, 0, 1, 1)

        self.retranslateUi(AppSellAbonement)
        QtCore.QMetaObject.connectSlotsByName(AppSellAbonement)

    def retranslateUi(self, AppSellAbonement):
        _translate = QtCore.QCoreApplication.translate
        AppSellAbonement.setWindowTitle(_translate("AppSellAbonement", "Продажа абонементов"))
        self.label.setText(_translate("AppSellAbonement", "Список абонементов"))
        self.sellButton.setText(_translate("AppSellAbonement", "Продать"))
        self.labelAbonement.setText(_translate("AppSellAbonement", "Id абонемента:"))
        self.oneDayCheckBox.setText(_translate("AppSellAbonement", "Разовое посещение"))
        self.labelDate.setText(_translate("AppSellAbonement", "Дата окончания\n"
"абонемента:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AppSellAbonement = QtWidgets.QWidget()
    ui = Ui_AppSellAbonement()
    ui.setupUi(AppSellAbonement)
    AppSellAbonement.show()
    sys.exit(app.exec_())
