# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\ui_app_rooms_capacity.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppRoomsCapacity(object):
    def setupUi(self, AppRoomsCapacity):
        AppRoomsCapacity.setObjectName("AppRoomsCapacity")
        AppRoomsCapacity.setWindowModality(QtCore.Qt.ApplicationModal)
        AppRoomsCapacity.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("design\\../../res/gym.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AppRoomsCapacity.setWindowIcon(icon)
        self.verticalLayoutWidget = QtWidgets.QWidget(AppRoomsCapacity)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 781, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.table = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.verticalLayout.addWidget(self.table)
        self.gridLayoutWidget = QtWidgets.QWidget(AppRoomsCapacity)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(230, 0, 271, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.chooseDateLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.chooseDateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.chooseDateLabel.setObjectName("chooseDateLabel")
        self.gridLayout.addWidget(self.chooseDateLabel, 0, 0, 1, 1)
        self.timesLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.timesLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timesLabel.setObjectName("timesLabel")
        self.gridLayout.addWidget(self.timesLabel, 1, 0, 1, 1)
        self.timesComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.timesComboBox.setObjectName("timesComboBox")
        self.gridLayout.addWidget(self.timesComboBox, 1, 1, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 0, 1, 1, 1)

        self.retranslateUi(AppRoomsCapacity)
        QtCore.QMetaObject.connectSlotsByName(AppRoomsCapacity)

    def retranslateUi(self, AppRoomsCapacity):
        _translate = QtCore.QCoreApplication.translate
        AppRoomsCapacity.setWindowTitle(_translate("AppRoomsCapacity", "Загруженность залов"))
        self.label.setText(_translate("AppRoomsCapacity", "Загруженность залов по состоянию на "))
        self.chooseDateLabel.setText(_translate("AppRoomsCapacity", "Дата:"))
        self.timesLabel.setText(_translate("AppRoomsCapacity", "Время:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AppRoomsCapacity = QtWidgets.QWidget()
    ui = Ui_AppRoomsCapacity()
    ui.setupUi(AppRoomsCapacity)
    AppRoomsCapacity.show()
    sys.exit(app.exec_())
