# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\ui_app_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppMain(object):
    def setupUi(self, AppMain):
        AppMain.setObjectName("AppMain")
        AppMain.resize(800, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("design\\../../res/gym.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AppMain.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(AppMain)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 781, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.appSellAbonementButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appSellAbonementButton.sizePolicy().hasHeightForWidth())
        self.appSellAbonementButton.setSizePolicy(sizePolicy)
        self.appSellAbonementButton.setObjectName("appSellAbonementButton")
        self.verticalLayout.addWidget(self.appSellAbonementButton)
        self.appDenyAbonementButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appDenyAbonementButton.sizePolicy().hasHeightForWidth())
        self.appDenyAbonementButton.setSizePolicy(sizePolicy)
        self.appDenyAbonementButton.setObjectName("appDenyAbonementButton")
        self.verticalLayout.addWidget(self.appDenyAbonementButton)
        self.appRoomsCapacityButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appRoomsCapacityButton.sizePolicy().hasHeightForWidth())
        self.appRoomsCapacityButton.setSizePolicy(sizePolicy)
        self.appRoomsCapacityButton.setObjectName("appRoomsCapacityButton")
        self.verticalLayout.addWidget(self.appRoomsCapacityButton)
        self.appFinancialReportButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appFinancialReportButton.sizePolicy().hasHeightForWidth())
        self.appFinancialReportButton.setSizePolicy(sizePolicy)
        self.appFinancialReportButton.setObjectName("appFinancialReportButton")
        self.verticalLayout.addWidget(self.appFinancialReportButton)
        AppMain.setCentralWidget(self.centralwidget)
        self.action = QtWidgets.QAction(AppMain)
        self.action.setObjectName("action")

        self.retranslateUi(AppMain)
        QtCore.QMetaObject.connectSlotsByName(AppMain)

    def retranslateUi(self, AppMain):
        _translate = QtCore.QCoreApplication.translate
        AppMain.setWindowTitle(_translate("AppMain", "Информационная система \"Фитнес\""))
        self.appSellAbonementButton.setText(_translate("AppMain", "Продать абонемент"))
        self.appDenyAbonementButton.setText(_translate("AppMain", "Отказ от абонемента"))
        self.appRoomsCapacityButton.setText(_translate("AppMain", "Загруженность залов"))
        self.appFinancialReportButton.setText(_translate("AppMain", "Финансовый отчет"))
        self.action.setText(_translate("AppMain", "Справка"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AppMain = QtWidgets.QMainWindow()
    ui = Ui_AppMain()
    ui.setupUi(AppMain)
    AppMain.show()
    sys.exit(app.exec_())
