# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\ui_app_deny_abonement.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppDenyAbonement(object):
    def setupUi(self, AppDenyAbonement):
        AppDenyAbonement.setObjectName("AppDenyAbonement")
        AppDenyAbonement.resize(600, 100)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("design\\../../res/gym.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AppDenyAbonement.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtWidgets.QWidget(AppDenyAbonement)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 571, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button.setObjectName("button")
        self.horizontalLayout.addWidget(self.button)

        self.retranslateUi(AppDenyAbonement)
        QtCore.QMetaObject.connectSlotsByName(AppDenyAbonement)

    def retranslateUi(self, AppDenyAbonement):
        _translate = QtCore.QCoreApplication.translate
        AppDenyAbonement.setWindowTitle(_translate("AppDenyAbonement", "Отказ от абонемента"))
        self.label.setText(_translate("AppDenyAbonement", "Id чека:"))
        self.button.setText(_translate("AppDenyAbonement", "Отказ от\n"
"абонемента"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AppDenyAbonement = QtWidgets.QWidget()
    ui = Ui_AppDenyAbonement()
    ui.setupUi(AppDenyAbonement)
    AppDenyAbonement.show()
    sys.exit(app.exec_())
